Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
