Style/Documentation:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
